### ISSUE TITLE
Error with PostCSS 8.2 / Next.js / Yarn 2

### ISSUE THREAD

**Issue by overlisted** [limitlessloop/flex-gap-polyfill#31]
Just wanted to try this polyfill and see if it will fix `flex-gap`s in Safari, but I'm getting this error:
```
> Build error occurred
Error: flex-gap-polyfill tried to access postcss-value-parser, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: postcss-value-parser (via "postcss-value-parser")
Required by: flex-gap-polyfill@virtual:8155a6cfbfdfb46993d4580fc21eff83d1d0b0104b30d90fc21cb3d1cb6af424a8c7374ff66963ea16d49d22220c7d865f663773d2ac91294d0e55ae2e9a274c#npm:2.2.1 (via /doc/overlisted/Projects/overlisted/website/.yarn/$$virtual/flex-gap-polyfill-virtual-4373d3db4f/0/cache/flex-gap-polyfill-npm-2.2.1-63f7eb63dc-e9a27e7b0f.zip/node_modules/flex-gap-polyfill/)

Require stack:
- /doc/overlisted/Projects/overlisted/website/.yarn/$$virtual/flex-gap-polyfill-virtual-4373d3db4f/0/cache/flex-gap-polyfill-npm-2.2.1-63f7eb63dc-e9a27e7b0f.zip/node_modules/flex-gap-polyfill/index.js
- ...
```

**Comment by limitlessloop** [comment]
Hi @overlisted thanks for reporting this. Could be something I've missed with the dependencies. You could try `npm install postcss-value-parser --save-dev` to if this resolves it. Meanwhile, I'll look into it further. Thanks!

**Comment by overlisted** [comment]
Installing that package has fixed that, so yeah, you're probably missing that dependency

**Comment by overlisted** [comment]
A question while we're at it: Is this plugin going to work with Tailwind? Because in Tailwind `flex` and `gap-*` are separate classes, I wonder how you will/did it.

**Comment by limitlessloop** [comment]
Hmm. Good question. The plugin currently only polyfills   when `display: flex/inline-flex` and `gap` exist in the same selector rule. This is to avoid it affecting CSS Grid. I'm also not sure if it would polyfill any of the Tailwind CSS. It's been a while since I used Tailwind and I can't remember how PostCSS plugins effect it.

For now the only thing I can think of to work around this would be to override the `.gap-* class which Tailwind provides with your own.

```
.flex.gap-* {
  display: flex;
  gap: *;
}
```

Maybe this can be done as part of Tailwinds customisation features?

**Comment by overlisted** [comment]
That's a great solution. We should ask what the Tailwind team thinks.

**Comment by limitlessloop** [comment]
Hi @overlisted. I'm working on an option that adds support for Tailwind. I'm still testing it at the moment, but if all goes well, should be available in the next release.

**Comment by overlisted** [comment]
Thank you! It would really come in handy!

**Comment by limitlessloop** [comment]
I can't guarantee I'll be able to make it perfect but I'll try my best. I've published a pre-release if you want to give it a go. Just install using `npm install flex-gap-polyfill@next --save-dev`.

Pass options through plugin as:
```js
module.exports = {
	plugins: {
		'tailwindcss': {},
		'flex-gap-polyfill': {
			tailwindCSS: true,
		}
	}
};
```

It currently works when the classes `flex` and `gap-*` are applied at the same time. I'll need to investigate what I can do when `margin` is applied, as `margin-left` and `margin-top` are used by the polyfill and will be overridden by Tailwind as it currently stands.

**Comment by overlisted** [comment]
Would there also be a way to make it apply the polyfill just on all non-grid elements? Because `display: flex` is set to all (reasonable) elements by default (with a CSS selector) in my project.

**Comment by overlisted** [comment]
(yeah sorry if this is becoming a sort of "everything this project lacks" issue at this point)

**Comment by limitlessloop** [comment]
That's ok. It would be quite costly to polyfill because it would have to replace every occurrence `margin` in every CSS rule. It needs something to narrow it down. That's why I should be able to provide support for Tailwind because I can check the selector to see if it matches `.gap*` and then assume that it's used with a class of `.flex`.

Could you tell me a bit more about your project and what you're using to name your classes? It's still pre-release so if I can abstract it to make it more applicable to different use cases I'll try.

Failing this you could try this JavaScript polyfill that @jonathantneal created.
https://cdpn.io/jonneal/debug/YzGxGvo

**Comment by overlisted** [comment]
I'm currently just trying out that concept in my personal website ([overlisted/website](https://github.com/overlisted/website)). This is the piece of CSS that makes everything a flexbox by default:
```css
html * {
  display: flex;
}

head *,
script,
style {
  display: none;
}
```

And here is a sample list of classnames for a simple list: `flex-col gap-2 md:gap-4` (`flex-row` classname is always omitted).

As you can see, there is no simple way to match that `gap-*` with the `display: flex`, so my idea is to make everything except the selector `.grid.gap-*` use this polyfill. It should obviously be an opt-in feature though.

**Comment by limitlessloop** [comment]
I tried something similar once, so I can see the appeal of wanting to use flex and gap universally with every element.

To support something like this would be extremely expensive because the polyfill covers so many use cases, to do this it has to add custom properties to every rule which has `flex`, `inline-flex`, `gap`, `margin`, `width` and `height`.  If I get time I'll experiment with making it more liberal but it would require some thought.

For the time being, I would definitely investigate if Jonathan's JavaScript polyfill could work.

Thanks again for your feedback and suggestion.

**Comment by limitlessloop** [comment]
Hi @overlisted . The polyfill now works with Tailwind by default. It's been rewritten from the ground up and may also work for you're use case of applying `flex` to every element, but I can't guarantee it. There are also some other new options in the readme which might come in handy.
